package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"fmt"

	"github.com/PrameshKarki/event-management-golang/graph/model"
	services "github.com/PrameshKarki/event-management-golang/graph/services/auth"
	userService "github.com/PrameshKarki/event-management-golang/graph/services/user"
	"github.com/PrameshKarki/event-management-golang/utils"
)

// UserSignUp is the resolver for the userSignUp field.
func (r *mutationResolver) UserSignUp(ctx context.Context, data model.UserInput) (*model.AuthSchema, error) {
	if err := utils.ValidateInput(data); err != nil {
		return nil, err
	}
	user := userService.FindOneByEmail(data.Email)
	if user.ID != "" {
		return nil, fmt.Errorf("User already exists")
	}
	userId, _ := services.UserSignUp(data)
	tokenMetaData := utils.TokenMetadata{ID: fmt.Sprint(userId), Email: data.Email}
	accessToken, _ := utils.SignAccessToken(tokenMetaData)
	return &model.AuthSchema{ID: fmt.Sprint(userId), AccessToken: accessToken, Email: data.Email}, nil
}

// UserLogin is the resolver for the userLogin field.
func (r *mutationResolver) UserLogin(ctx context.Context, data model.LoginInput) (*model.AuthSchema, error) {
	user := userService.FindOneByEmail(data.Email)
	if user.ID == "" {
		return nil, fmt.Errorf("invalid credentials")
	}
	err := utils.ComparePassword(user.Password, data.Password)
	if err != nil {
		return nil, fmt.Errorf("invalid credentials")
	}
	tokenMetaData := utils.TokenMetadata{ID: user.ID, Email: user.Email}
	accessToken, _ := utils.SignAccessToken(tokenMetaData)
	return &model.AuthSchema{ID: user.ID, AccessToken: accessToken, Email: data.Email}, nil
}
