// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddMemberInput struct {
	Members []*MemberInput `json:"members"`
}

type AuthSchema struct {
	AccessToken string `json:"accessToken"`
	ID          string `json:"id"`
	Email       string `json:"email"`
}

type Event struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	StartDate   string  `json:"startDate"`
	Location    string  `json:"location"`
	Description *string `json:"description,omitempty"`
	EndDate     string  `json:"endDate"`
	CreatedBy   *User   `json:"createdBy"`
}

type EventInput struct {
	Name        string  `json:"name" validate:"required"`
	StartDate   string  `json:"startDate" validate:"required"`
	Description *string `json:"description,omitempty"`
	EndDate     string  `json:"endDate" validate:"required"`
	Location    string  `json:"location" validate:"required"`
}

type EventResponse struct {
	ID *int `json:"id,omitempty"`
}

type Expense struct {
	ID          string  `json:"id"`
	ItemName    string  `json:"itemName"`
	Cost        float64 `json:"cost"`
	Description *string `json:"description,omitempty"`
	Category    string  `json:"category"`
}

type ExpenseInput struct {
	ItemName    string  `json:"itemName"`
	Cost        float64 `json:"cost"`
	Description *string `json:"description,omitempty"`
	Category    string  `json:"category"`
}

type ExpenseWithEvent struct {
	ID          string  `json:"id"`
	ItemName    string  `json:"itemName"`
	Cost        float64 `json:"cost"`
	Description *string `json:"description,omitempty"`
	Category    string  `json:"category"`
	Event       *Event  `json:"event"`
}

type ExpensesByCategory struct {
	Category string  `json:"category"`
	Total    float64 `json:"total"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Member struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phoneNumber"`
	Role        string `json:"role"`
}

type MemberInput struct {
	ID   string `json:"id" validate:"required"`
	Role string `json:"role" validate:"required"`
}

type Response struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type ScheduleUpdateInput struct {
	StartDate string `json:"startDate" validate:"required"`
	EndDate   string `json:"endDate" validate:"required"`
}

type Session struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	StartTime   string  `json:"startTime"`
	EndTime     string  `json:"endTime"`
	Description *string `json:"description,omitempty"`
}

type SessionInput struct {
	Name        string  `json:"name"`
	StartTime   string  `json:"startTime"`
	EndTime     string  `json:"endTime"`
	Description *string `json:"description,omitempty"`
}

type User struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phoneNumber"`
	Password    string `json:"password"`
}

type UserInput struct {
	Name        string `json:"name" validate:"required"`
	Email       string `json:"email" validate:"required,email"`
	PhoneNumber string `json:"phoneNumber" validate:"required"`
	Password    string `json:"password" validate:"required"`
}

type UserResponse struct {
	ID *int `json:"id,omitempty"`
}
